const emojiMap = {
    "happy": "😊",
    "sad": "😢",
    "love": "❤️",
    "food": "🍔",
    "cat": "🐱",
    "dog": "🐶",
    "party": "🎉",
    "heart": "💖",
    "sun": "☀️",
    "moon": "🌙",
    "fire": "🔥",
    "thumbs up": "👍",
    "peace": "✌️",
    "money": "💰",
    "star": "⭐",
    "book": "📚",
    "coffee": "☕",
    "music": "🎶",
    "rocket": "🚀",
    "100": "💯",
    "dance": "💃",
    "baby": "👶",
    "smile": "😄",
    "wink": "😉",
    "angry": "😠",
    "confused": "😕",
    "tired": "😴",
    "surprised": "😮",
    "sunglasses": "😎",
    "clap": "👏",
    "thumbs down": "👎",
    "praying": "🙏",
    "sick": "🤒",
    "ninja": "🥷",
    "wizard": "🧙‍♂️",
    "vampire": "🧛‍♂️",
    "zombie": "🧟‍♂️",
    "cactus": "🌵",
    "tree": "🌳",
    "flower": "🌼",
    "rain": "🌧️",
    "snow": "❄️",
    "cloud": "☁️",
    "rainbow": "🌈",
    "pizza": "🍕",
    "burger": "🍔",
    "cake": "🍰",
    "ice cream": "🍦",
    "pasta": "🍝",
    "sushi": "🍣",
    "popcorn": "🍿",
    "beer": "🍺",
    "wine": "🍷",
    "cocktail": "🍸",
    "champagne": "🍾",
    "hotdog": "🌭",
    "cookie": "🍪",
    "chocolate": "🍫",
    "sweet potato": "🍠",
    "egg": "🥚",
    "chicken": "🍗",
    "fish": "🐟",
    "shrimp": "🍤",
    "cherries": "🍒",
    "banana": "🍌",
    "grapes": "🍇",
    "apple": "🍎",
    "orange": "🍊",
    "lemon": "🍋",
    "watermelon": "🍉",
    "avocado": "🥑",
    "carrot": "🥕",
    "pepper": "🌶️",
    "potato": "🥔",
    "broccoli": "🥦",
    "eggplant": "🍆",
    "bacon": "🥓",
    "corn": "🌽",
    "cucumber": "🥒",
    "cupcake": "🧁",
    "birthday": "🎂",
    "graduation": "🎓",
    "travel": "✈️",
    "beach": "🏖️",
    "mountain": "🏔️",
    "city": "🏙️",
    "house": "🏠",
    "car": "🚗",
    "bus": "🚌",
    "bicycle": "🚴‍♂️",
    "train": "🚆",
    "rocket": "🚀",
    "trophy": "🏆",
    "medal": "🏅",
    "soccer": "⚽",
    "basketball": "🏀",
    "baseball": "⚾",
    "football": "🏈",
    "golf": "⛳",
    "swimming": "🏊‍♂️",
    "running": "🏃‍♂️",
    "hiking": "🥾",
    "fishing": "🎣",
    "climbing": "🧗‍♂️",
    "yoga": "🧘‍♀️"
};

// Function to translate text to emojis
document.getElementById("translate-button").addEventListener("click", function() {
    const inputText = document.getElementById("input-text").value.toLowerCase();
    let translatedText = inputText;

    // Replace words with emojis
    for (const [word, emoji] of Object.entries(emojiMap)) {
        const regex = new RegExp(`\\b${word}\\b`, "g");
        translatedText = translatedText.replace(regex, emoji);
    }

    document.getElementById("emoji-display").innerText = translatedText || "Please enter some text!";
});

// Clear input and output
document.getElementById("clear-button").addEventListener("click", function() {
    document.getElementById("input-text").value = '';
    document.getElementById("emoji-display").innerText = '';
});
